### ISSUE TITLE
新增用户失败

### ISSUE THREAD

**Issue by zhuxindong** [nianhua99/PandoraNext-Helper#25]
容器日志 
```
DEBUG:apscheduler.scheduler:No jobs; waiting until a job is added
INFO:waitress:Serving on http://0.0.0.0:8182
2023-12-27 17:13:47.465 | ERROR    | main.main:refresh:146 - Expecting value: line 1 column 1 (char 0)
ERROR:app:Exception on /openchat1227/sync [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/app/main/main.py", line 293, in sync
    sync_pandora()
  File "/app/main/main.py", line 286, in sync_pandora
    pandora_tools.fresh_setup()
  File "/app/pandora_tools.py", line 17, in fresh_setup
    logger.info("重载：{}", response.json())
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-12-27 17:14:09.734 | ERROR    | main.main:refresh:146 - Expecting value: line 1 column 1 (char 0)
2023-12-27 17:15:35.211 | ERROR    | main.main:refresh:146 - Expecting value: line 1 column 1 (char 0)
2023-12-27 17:17:33.979 | ERROR    | main.main:refresh:146 - Expecting value: line 1 column 1 (char 0)
2023-12-27 17:19:55.887 | ERROR    | main.main:refresh:146 - Expecting value: line 1 column 1 (char 0)

```

**Comment by nianhua99** [comment]
看样子是同步接口的问题，不是新增用户的问题？
