### ISSUE TITLE
在点击同步到pandoranext之后，跳转会报错

### ISSUE THREAD

**Issue by Payne-Wang** [nianhua99/PandoraNext-Helper#44]
![image](https://github.com/nianhua99/PandoraNext-Helper/assets/44337721/c53e12e2-b68b-447b-868c-2aceab462428)

**Comment by Payne-Wang** [comment]
我是使用python部署的，报错信息如下：
ERROR:app:Exception on /2023mmcb1234/sync [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/ubuntu/pandora/PandoraNext-Helper/main/main.py", line 382, in sync
    sync_pandora()
  File "/home/ubuntu/pandora/PandoraNext-Helper/main/main.py", line 374, in sync_pandora
    make_json()
  File "/home/ubuntu/pandora/PandoraNext-Helper/main/main.py", line 331, in make_json
    tokens = {k: v for k, v in tokens.items() if 'token' in v and not v['token'].startswith('fk')}
  File "/home/ubuntu/pandora/PandoraNext-Helper/main/main.py", line 331, in <dictcomp>
    tokens = {k: v for k, v in tokens.items() if 'token' in v and not v['token'].startswith('fk')}
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by nianhua99** [comment]
你现在的tokens.json里是不是有空token

**Comment by Payne-Wang** [comment]
> 你现在的tokens.json里是不是有空token

没有，只有两个test的token，而且它们都能登陆

**Comment by Payne-Wang** [comment]
> 你现在的tokens.json里是不是有空token

不好意思，刚才检查了一下，确实有个测试过程中被误导入的空token，现在解决了，谢谢大佬
