### ISSUE TITLE
docker 0.7.0 無法使用

### ISSUE THREAD

**Issue by jasonwu1994** [nianhua99/PandoraNext-Helper#53]
Arm架構，啟用報錯

```
ERROR:apscheduler.jobstores.default:Unable to restore job "my_job" -- removing it
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/apscheduler/util.py", line 271, in ref_to_obj
    obj = __import__(modulename, fromlist=[rest])
ModuleNotFoundError: No module named 'main.main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/apscheduler/jobstores/sqlalchemy.py", line 148, in _get_jobs
    jobs.append(self._reconstitute_job(row.job_state))
  File "/usr/local/lib/python3.9/site-packages/apscheduler/jobstores/sqlalchemy.py", line 134, in _reconstitute_job
    job.__setstate__(job_state)
  File "/usr/local/lib/python3.9/site-packages/apscheduler/job.py", line 273, in __setstate__
    self.func = ref_to_obj(self.func_ref)
  File "/usr/local/lib/python3.9/site-packages/apscheduler/util.py", line 273, in ref_to_obj
    raise LookupError('Error resolving reference %s: could not import module' % ref)
LookupError: Error resolving reference main.main:refresh_all_user: could not import module
```

**Comment by jasonwu1994** [comment]
"解除了 api_proxy_prefix 的前缀，你现在访问端口可以直接使用本项目"
