### ISSUE TITLE
刷新账号失败

### ISSUE THREAD

**Issue by zhuxindong** [nianhua99/PandoraNext-Helper#56]
刷新账号失败

```log
2024-01-15 16:05:46.877 | INFO     | util.login_tools:get_access_token_by_refresh_token:73 - 获取access_token结果：{"access_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJzYW10aW1wdGVybWlzZUAxMjM1ODAueHl6IiwiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJodHRwczovL2FwaS5vcGVuYWkuY29tL2F1dGgiOnsicG9pZCI6Im9yZy1Ea0RDb3R6VHRiVkpXSGMzd2hMeVBXcGwiLCJ1c2VyX2lkIjoidXNlci1VMkZ0WnE0emtJTWt2bXROZHN3RHppcG4ifSwiaXNzIjoiaHR0cHM6Ly9hdXRoMC5vcGVuYWkuY29tLyIsInN1YiI6ImF1dGgwfDY1OGU1ZWViZmI3Nzc5ZTVlYjU1NDM4YSIsImF1ZCI6WyJodHRwczovL2FwaS5vcGVuYWkuY29tL3YxIiwiaHR0cHM6Ly9vcGVuYWkub3BlbmFpLmF1dGgwYXBwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE3MDUzMDU5NDYsImV4cCI6MTcwNjE2OTk0NiwiYXpwIjoicGRsTElYMlk3Mk1JbDJyaExoVEU5VlY5Yk45MDVrQmgiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIG1vZGVsLnJlYWQgbW9kZWwucmVxdWVzdCBvcmdhbml6YXRpb24ucmVhZCBvZmZsaW5lX2FjY2VzcyJ9.UAniXmhPKbXDYiwP9MM0daQwg-DX5BoWko2N11yRTAnvemraJ9KYSRlB0d3jgVTdtEh2S-RBSLQ7mNG9Ul5lD0m51Sn_Q8EngOLk88_7f-xSZMB_CCIg1jhgFhXM1VZYmUfasPPWBxFke1p2fbrSobvd9byz4eLwhfm7C6Ddf6p7VRKAIz5fFyohYLgmN3Omz4A2du0mR4AVvOkmSC0zvk7LD_76nHZe4b-uSfqRXG1b6lnLOoJQEZwqGjb1aQohuGLl6yP9mxo6a2uKIu8GKyb6IkK332i9FYvRw500nxBrhkaUla5LkpDqNTDNBcxiTj7_KLY2EiqBFMNtLhN4Mw","expires_in":864000,"id_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL2F1dGgiOnsiZ3JvdXBzIjpbXSwib3JnYW5pemF0aW9ucyI6W3siaWQiOiJvcmctRGtEQ290elR0YlZKV0hjM3doTHlQV3BsIiwiaXNfZGVmYXVsdCI6dHJ1ZSwicm9sZSI6Im93bmVyIiwidGl0bGUiOiJQZXJzb25hbCJ9XSwidXNlcl9pZCI6InVzZXItVTJGdFpxNHprSU1rdm10TmRzd0R6aXBuIn0sIm5pY2tuYW1lIjoic2FtdGltcHRlcm1pc2UiLCJuYW1lIjoic2FtdGltcHRlcm1pc2VAMTIzNTgwLnh5eiIsInBpY3R1cmUiOiJodHRwczovL3MuZ3JhdmF0YXIuY29tL2F2YXRhci9kYWIyOWEzNDhiNDcxM2Q2OTRlZjNmZGFlYWJkYTMxOD9zPTQ4MCZyPXBnJmQ9aHR0cHMlM0ElMkYlMkZjZG4uYXV0aDAuY29tJTJGYXZhdGFycyUyRnNhLnBuZyIsInVwZGF0ZWRfYXQiOiIyMDI0LTAxLTA0VDA5OjA2OjQzLjE2N1oiLCJlbWFpbCI6InNhbXRpbXB0ZXJtaXNlQDEyMzU4MC54eXoiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9hdXRoMC5vcGVuYWkuY29tLyIsImF1ZCI6InBkbExJWDJZNzJNSWwycmhMaFRFOVZWOWJOOTA1a0JoIiwiaWF0IjoxNzA1MzA1OTQ2LCJleHAiOjE3MDUzNDE5NDYsInN1YiI6ImF1dGgwfDY1OGU1ZWViZmI3Nzc5ZTVlYjU1NDM4YSIsInNpZCI6Ik1hZXRfX3g5M05IUmJIZGpPNWVIblYwNUw4ZVNDM2xyIn0.PIAMyaZb3ReJFekemmtaZEfFz7ZuOxp-9TKjDfEfuLB8IxbxZJlBAjdEGiGEgWL-cNHUhEmtixcUTDYxUozvV1k7tgb8wtnx3LyuJ_NfEG5T0_zLxT_AZId7LPuHLfZwRKtqR0VOXZs3Oa7H_ty7bRXViaUQG_LxC9k39ZMzBFdfmSY-42clis-mSA5UhMDvLUfYCsOPU1YKnSAUhRISQslOII7DWw4UbddLwPjosVBH5GyJUhnlKoWlOCbUaDAQV2Jx8RsO8YaASMsqEWxbpJn-z_VYGZVqDUiSWTZobZaGcAY54pKXGMNcblpO9tWH2-sorlYysh9kReK5f_CVgA","scope":"openid profile email model.read model.request organization.read offline_access","token_type":"Bearer"},200
ERROR:app:Exception on /api/account/refresh [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "/app/account/account.py", line 123, in account_refresh
    sync_pandora()
  File "/app/util/pandora_tools.py", line 120, in sync_pandora
    make_json()
  File "/app/util/pandora_tools.py", line 77, in make_json
    tokens = {k: v for k, v in tokens.items() if 'token' in v and not v['token'].startswith('fk')}
  File "/app/util/pandora_tools.py", line 77, in <dictcomp>
    tokens = {k: v for k, v in tokens.items() if 'token' in v and not v['token'].startswith('fk')}
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by emtry** [comment]
+1

**Comment by oneCatZz** [comment]
更新和添加都会有这个错

**Comment by 7788jay** [comment]
+1

**Comment by lddcc** [comment]
![image](https://github.com/nianhua99/PandoraNext-Helper/assets/59772256/bb7f00b0-a154-4874-a19b-a641b718706f)
打开pandora-next的token.json配置文件，把里面的异常数据删掉应该就可以了

**Comment by nianhua99** [comment]
已修复，更新到 0.7.0_rc1 就好
